[build]
  # Base directory
  base = "."

  # Publish directory
  publish = "public"

  # Build command
  command = "composer install --no-dev --optimize-autoloader --ignore-platform-reqs && npm ci && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[build.environment]
  # PHP version
  PHP_VERSION = "8.2"
  
  # Node version - LTS for stability
  NODE_VERSION = "20"
  
  # NPM version
  NPM_VERSION = "10"

# Redirects for Laravel routing
[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
