version: '3.8'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: railway_password_123
      MYSQL_DATABASE: managemen
      MYSQL_USER: railway
      MYSQL_PASSWORD: railway_password_123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: [
      "mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--innodb-buffer-pool-size=128M",
      "--max-connections=100",
      "--skip-log-bin"
    ]
    restart: unless-stopped

volumes:
  mysql_data:
