[build]
  # Base directory
  base = "."

  # Publish directory
  publish = "public"

  # Build command for Laravel with Neon database
  command = "composer install --no-dev --optimize-autoloader && npm install && npm run build && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[build.environment]
  # PHP version
  PHP_VERSION = "8.2"
  
  # Node version
  NODE_VERSION = "20"

# Function configuration for serverless PHP
[functions]
  directory = "netlify/functions"

# Redirects for Laravel routing
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/laravel/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline';"

# Environment variables (akan diisi di Netlify dashboard)
[context.production.environment]
  APP_ENV = "production"
  APP_DEBUG = "false"
  LOG_LEVEL = "error"
